### ISSUE TITLE
Leaking OAUTH token of another player after using Rimworld Multiplayer

### ISSUE THREAD

**Issue by meffcio** [hodldeeznuts/ToolkitCore#9]
1. A friend of mine was using ToolkitCore + Twitch Toolkit on some of his RimWorld streams
2. Some time later we ended up playing a coop game of RimWorld using the mod Rimworld Multiplayer (only with the necessary Harmony mod turned on - ToolkitCore and Twitch Toolkit were disabled on his side, and I didn't even have them installed)
3. Then another day I installed ToolkitCore + Twitch Toolkit to look around the settings and learn what can be done with the mod.
4. When I opened up ToolkitCore's settings I saw my friend's channel name and bot name set there, **as well as his oauth token** - the mod immediately connected my game to his chat as his bot.

**Comment by SirRandoo** [comment]
This isn't inherently a ToolkitCore issue. While the mod does use RimWorld's mod settings code to store credentials, the Multiplayer mod is responsible for distributing the file they're stored in since their [bandaid](https://github.com/rwmt/Multiplayer/blob/7aac8b54727d8626ec39429b97225fc88c807ab8/Source/Client/ModManagement.cs#L209) was never updated to filter ToolkitCore's settings.
